name: Jest Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        meteor: [ '2.8.0' ]

    steps:
    - uses: actions/checkout@v1
    - uses: codecov/codecov-action@v3
    
    - name: Use Meteor.js ${{ matrix.meteor }}
      uses: meteorengineer/setup-meteor@v1.0.3
      with:
        meteor-release: ${{ matrix.meteor }}
    - run: meteor npm install
    - run: npm run coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/lcov-report/
        flags: unittests
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
